#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DpFinanciamentos")]
	public partial class PIMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCADASTRO(CADASTRO instance);
    partial void UpdateCADASTRO(CADASTRO instance);
    partial void DeleteCADASTRO(CADASTRO instance);
    partial void InsertLOGIN(LOGIN instance);
    partial void UpdateLOGIN(LOGIN instance);
    partial void DeleteLOGIN(LOGIN instance);
    partial void InsertPAGAMENTO(PAGAMENTO instance);
    partial void UpdatePAGAMENTO(PAGAMENTO instance);
    partial void DeletePAGAMENTO(PAGAMENTO instance);
    partial void InsertEndereco(Endereco instance);
    partial void UpdateEndereco(Endereco instance);
    partial void DeleteEndereco(Endereco instance);
    partial void InsertCONTRATO(CONTRATO instance);
    partial void UpdateCONTRATO(CONTRATO instance);
    partial void DeleteCONTRATO(CONTRATO instance);
    #endregion
		
		public PIMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DpFinanciamentosConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PIMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BOLETO> BOLETOs
		{
			get
			{
				return this.GetTable<BOLETO>();
			}
		}
		
		public System.Data.Linq.Table<CADASTRO> CADASTROs
		{
			get
			{
				return this.GetTable<CADASTRO>();
			}
		}
		
		public System.Data.Linq.Table<LOGIN> LOGINs
		{
			get
			{
				return this.GetTable<LOGIN>();
			}
		}
		
		public System.Data.Linq.Table<PAGAMENTO> PAGAMENTOs
		{
			get
			{
				return this.GetTable<PAGAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<Endereco> Enderecos
		{
			get
			{
				return this.GetTable<Endereco>();
			}
		}
		
		public System.Data.Linq.Table<CONTRATO> CONTRATOs
		{
			get
			{
				return this.GetTable<CONTRATO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOLETOS")]
	public partial class BOLETO
	{
		
		private int _BOLETOid;
		
		private string _CAD_NOME;
		
		private string _CPFCNPJ;
		
		private int _PGTO_PARCELA_NUM;
		
		private double _VALOR;
		
		private int _CADid;
		
		private System.Nullable<System.DateTime> _DT_PGTO;
		
		private System.DateTime _DT_VENCIMENTO;
		
		private string _status;
		
		public BOLETO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOLETOid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int BOLETOid
		{
			get
			{
				return this._BOLETOid;
			}
			set
			{
				if ((this._BOLETOid != value))
				{
					this._BOLETOid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD_NOME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CAD_NOME
		{
			get
			{
				return this._CAD_NOME;
			}
			set
			{
				if ((this._CAD_NOME != value))
				{
					this._CAD_NOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCNPJ", DbType="VarChar(15)")]
		public string CPFCNPJ
		{
			get
			{
				return this._CPFCNPJ;
			}
			set
			{
				if ((this._CPFCNPJ != value))
				{
					this._CPFCNPJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_PARCELA_NUM", DbType="Int NOT NULL")]
		public int PGTO_PARCELA_NUM
		{
			get
			{
				return this._PGTO_PARCELA_NUM;
			}
			set
			{
				if ((this._PGTO_PARCELA_NUM != value))
				{
					this._PGTO_PARCELA_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Float NOT NULL")]
		public double VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this._VALOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CADid", DbType="Int NOT NULL")]
		public int CADid
		{
			get
			{
				return this._CADid;
			}
			set
			{
				if ((this._CADid != value))
				{
					this._CADid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_PGTO", DbType="Date")]
		public System.Nullable<System.DateTime> DT_PGTO
		{
			get
			{
				return this._DT_PGTO;
			}
			set
			{
				if ((this._DT_PGTO != value))
				{
					this._DT_PGTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_VENCIMENTO", DbType="Date NOT NULL")]
		public System.DateTime DT_VENCIMENTO
		{
			get
			{
				return this._DT_VENCIMENTO;
			}
			set
			{
				if ((this._DT_VENCIMENTO != value))
				{
					this._DT_VENCIMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(40)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CADASTRO")]
	public partial class CADASTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CADid;
		
		private string _CAD_NOME;
		
		private string _CAD_FANTASIA;
		
		private string _CPFCNPJ;
		
		private string _rgInscricao;
		
		private System.DateTime _DTN_Fundacao;
		
		private string _EMAIL;
		
		private string _CELULAR;
		
		private decimal _TEL_COMERCIAL;
		
		private string _FlAtivo;
		
		private string _DsAtivo;
		
		private EntitySet<LOGIN> _LOGINs;
		
		private EntitySet<Endereco> _Enderecos;
		
		private EntitySet<CONTRATO> _CONTRATOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCADidChanging(int value);
    partial void OnCADidChanged();
    partial void OnCAD_NOMEChanging(string value);
    partial void OnCAD_NOMEChanged();
    partial void OnCAD_FANTASIAChanging(string value);
    partial void OnCAD_FANTASIAChanged();
    partial void OnCPFCNPJChanging(string value);
    partial void OnCPFCNPJChanged();
    partial void OnrgInscricaoChanging(string value);
    partial void OnrgInscricaoChanged();
    partial void OnDTN_FundacaoChanging(System.DateTime value);
    partial void OnDTN_FundacaoChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnTEL_COMERCIALChanging(decimal value);
    partial void OnTEL_COMERCIALChanged();
    partial void OnFlAtivoChanging(string value);
    partial void OnFlAtivoChanged();
    partial void OnDsAtivoChanging(string value);
    partial void OnDsAtivoChanged();
    #endregion
		
		public CADASTRO()
		{
			this._LOGINs = new EntitySet<LOGIN>(new Action<LOGIN>(this.attach_LOGINs), new Action<LOGIN>(this.detach_LOGINs));
			this._Enderecos = new EntitySet<Endereco>(new Action<Endereco>(this.attach_Enderecos), new Action<Endereco>(this.detach_Enderecos));
			this._CONTRATOs = new EntitySet<CONTRATO>(new Action<CONTRATO>(this.attach_CONTRATOs), new Action<CONTRATO>(this.detach_CONTRATOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CADid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CADid
		{
			get
			{
				return this._CADid;
			}
			set
			{
				if ((this._CADid != value))
				{
					this.OnCADidChanging(value);
					this.SendPropertyChanging();
					this._CADid = value;
					this.SendPropertyChanged("CADid");
					this.OnCADidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD_NOME", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string CAD_NOME
		{
			get
			{
				return this._CAD_NOME;
			}
			set
			{
				if ((this._CAD_NOME != value))
				{
					this.OnCAD_NOMEChanging(value);
					this.SendPropertyChanging();
					this._CAD_NOME = value;
					this.SendPropertyChanged("CAD_NOME");
					this.OnCAD_NOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD_FANTASIA", DbType="VarChar(45)")]
		public string CAD_FANTASIA
		{
			get
			{
				return this._CAD_FANTASIA;
			}
			set
			{
				if ((this._CAD_FANTASIA != value))
				{
					this.OnCAD_FANTASIAChanging(value);
					this.SendPropertyChanging();
					this._CAD_FANTASIA = value;
					this.SendPropertyChanged("CAD_FANTASIA");
					this.OnCAD_FANTASIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCNPJ", DbType="VarChar(15)")]
		public string CPFCNPJ
		{
			get
			{
				return this._CPFCNPJ;
			}
			set
			{
				if ((this._CPFCNPJ != value))
				{
					this.OnCPFCNPJChanging(value);
					this.SendPropertyChanging();
					this._CPFCNPJ = value;
					this.SendPropertyChanged("CPFCNPJ");
					this.OnCPFCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rgInscricao", DbType="NVarChar(15)")]
		public string rgInscricao
		{
			get
			{
				return this._rgInscricao;
			}
			set
			{
				if ((this._rgInscricao != value))
				{
					this.OnrgInscricaoChanging(value);
					this.SendPropertyChanging();
					this._rgInscricao = value;
					this.SendPropertyChanged("rgInscricao");
					this.OnrgInscricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTN_Fundacao", DbType="Date NOT NULL")]
		public System.DateTime DTN_Fundacao
		{
			get
			{
				return this._DTN_Fundacao;
			}
			set
			{
				if ((this._DTN_Fundacao != value))
				{
					this.OnDTN_FundacaoChanging(value);
					this.SendPropertyChanging();
					this._DTN_Fundacao = value;
					this.SendPropertyChanged("DTN_Fundacao");
					this.OnDTN_FundacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL_COMERCIAL", DbType="Decimal(18,0) NOT NULL")]
		public decimal TEL_COMERCIAL
		{
			get
			{
				return this._TEL_COMERCIAL;
			}
			set
			{
				if ((this._TEL_COMERCIAL != value))
				{
					this.OnTEL_COMERCIALChanging(value);
					this.SendPropertyChanging();
					this._TEL_COMERCIAL = value;
					this.SendPropertyChanged("TEL_COMERCIAL");
					this.OnTEL_COMERCIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlAtivo", DbType="VarChar(1)")]
		public string FlAtivo
		{
			get
			{
				return this._FlAtivo;
			}
			set
			{
				if ((this._FlAtivo != value))
				{
					this.OnFlAtivoChanging(value);
					this.SendPropertyChanging();
					this._FlAtivo = value;
					this.SendPropertyChanged("FlAtivo");
					this.OnFlAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DsAtivo", DbType="VarChar(40)")]
		public string DsAtivo
		{
			get
			{
				return this._DsAtivo;
			}
			set
			{
				if ((this._DsAtivo != value))
				{
					this.OnDsAtivoChanging(value);
					this.SendPropertyChanging();
					this._DsAtivo = value;
					this.SendPropertyChanged("DsAtivo");
					this.OnDsAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_LOGIN", Storage="_LOGINs", ThisKey="CADid", OtherKey="CADid")]
		public EntitySet<LOGIN> LOGINs
		{
			get
			{
				return this._LOGINs;
			}
			set
			{
				this._LOGINs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_Endereco", Storage="_Enderecos", ThisKey="CADid", OtherKey="CADid")]
		public EntitySet<Endereco> Enderecos
		{
			get
			{
				return this._Enderecos;
			}
			set
			{
				this._Enderecos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_CONTRATO", Storage="_CONTRATOs", ThisKey="CADid", OtherKey="CADid")]
		public EntitySet<CONTRATO> CONTRATOs
		{
			get
			{
				return this._CONTRATOs;
			}
			set
			{
				this._CONTRATOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOGINs(LOGIN entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = this;
		}
		
		private void detach_LOGINs(LOGIN entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = null;
		}
		
		private void attach_Enderecos(Endereco entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = this;
		}
		
		private void detach_Enderecos(Endereco entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = null;
		}
		
		private void attach_CONTRATOs(CONTRATO entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = this;
		}
		
		private void detach_CONTRATOs(CONTRATO entity)
		{
			this.SendPropertyChanging();
			entity.CADASTRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOGIN")]
	public partial class LOGIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LOGINid;
		
		private string _LOGIN1;
		
		private System.Nullable<int> _CADid;
		
		private string _NOME;
		
		private string _CPFCNPJ;
		
		private string _E_MAIL;
		
		private string _SENHA;
		
		private System.Nullable<int> _TIPOUSER;
		
		private EntityRef<CADASTRO> _CADASTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOGINidChanging(int value);
    partial void OnLOGINidChanged();
    partial void OnLOGIN1Changing(string value);
    partial void OnLOGIN1Changed();
    partial void OnCADidChanging(System.Nullable<int> value);
    partial void OnCADidChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnCPFCNPJChanging(string value);
    partial void OnCPFCNPJChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnTIPOUSERChanging(System.Nullable<int> value);
    partial void OnTIPOUSERChanged();
    #endregion
		
		public LOGIN()
		{
			this._CADASTRO = default(EntityRef<CADASTRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGINid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LOGINid
		{
			get
			{
				return this._LOGINid;
			}
			set
			{
				if ((this._LOGINid != value))
				{
					this.OnLOGINidChanging(value);
					this.SendPropertyChanging();
					this._LOGINid = value;
					this.SendPropertyChanged("LOGINid");
					this.OnLOGINidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LOGIN", Storage="_LOGIN1", DbType="NVarChar(50)")]
		public string LOGIN1
		{
			get
			{
				return this._LOGIN1;
			}
			set
			{
				if ((this._LOGIN1 != value))
				{
					this.OnLOGIN1Changing(value);
					this.SendPropertyChanging();
					this._LOGIN1 = value;
					this.SendPropertyChanged("LOGIN1");
					this.OnLOGIN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CADid", DbType="Int")]
		public System.Nullable<int> CADid
		{
			get
			{
				return this._CADid;
			}
			set
			{
				if ((this._CADid != value))
				{
					if (this._CADASTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCADidChanging(value);
					this.SendPropertyChanging();
					this._CADid = value;
					this.SendPropertyChanged("CADid");
					this.OnCADidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCNPJ", DbType="VarChar(15)")]
		public string CPFCNPJ
		{
			get
			{
				return this._CPFCNPJ;
			}
			set
			{
				if ((this._CPFCNPJ != value))
				{
					this.OnCPFCNPJChanging(value);
					this.SendPropertyChanging();
					this._CPFCNPJ = value;
					this.SendPropertyChanged("CPFCNPJ");
					this.OnCPFCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-MAIL]", Storage="_E_MAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOUSER", DbType="Int")]
		public System.Nullable<int> TIPOUSER
		{
			get
			{
				return this._TIPOUSER;
			}
			set
			{
				if ((this._TIPOUSER != value))
				{
					this.OnTIPOUSERChanging(value);
					this.SendPropertyChanging();
					this._TIPOUSER = value;
					this.SendPropertyChanged("TIPOUSER");
					this.OnTIPOUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_LOGIN", Storage="_CADASTRO", ThisKey="CADid", OtherKey="CADid", IsForeignKey=true)]
		public CADASTRO CADASTRO
		{
			get
			{
				return this._CADASTRO.Entity;
			}
			set
			{
				CADASTRO previousValue = this._CADASTRO.Entity;
				if (((previousValue != value) 
							|| (this._CADASTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CADASTRO.Entity = null;
						previousValue.LOGINs.Remove(this);
					}
					this._CADASTRO.Entity = value;
					if ((value != null))
					{
						value.LOGINs.Add(this);
						this._CADid = value.CADid;
					}
					else
					{
						this._CADid = default(Nullable<int>);
					}
					this.SendPropertyChanged("CADASTRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAGAMENTO")]
	public partial class PAGAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PGTOid;
		
		private System.Nullable<int> _CONTRATOid;
		
		private int _PGTO_PARCELA_NUM;
		
		private System.DateTime _DATA;
		
		private double _VALOR;
		
		private bool _PAGTO_STATUS;
		
		private string _CONTRATO_VENC;
		
		private EntityRef<CONTRATO> _CONTRATO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPGTOidChanging(int value);
    partial void OnPGTOidChanged();
    partial void OnCONTRATOidChanging(System.Nullable<int> value);
    partial void OnCONTRATOidChanged();
    partial void OnPGTO_PARCELA_NUMChanging(int value);
    partial void OnPGTO_PARCELA_NUMChanged();
    partial void OnDATAChanging(System.DateTime value);
    partial void OnDATAChanged();
    partial void OnVALORChanging(double value);
    partial void OnVALORChanged();
    partial void OnPAGTO_STATUSChanging(bool value);
    partial void OnPAGTO_STATUSChanged();
    partial void OnCONTRATO_VENCChanging(string value);
    partial void OnCONTRATO_VENCChanged();
    #endregion
		
		public PAGAMENTO()
		{
			this._CONTRATO = default(EntityRef<CONTRATO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTOid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PGTOid
		{
			get
			{
				return this._PGTOid;
			}
			set
			{
				if ((this._PGTOid != value))
				{
					this.OnPGTOidChanging(value);
					this.SendPropertyChanging();
					this._PGTOid = value;
					this.SendPropertyChanged("PGTOid");
					this.OnPGTOidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATOid", DbType="Int")]
		public System.Nullable<int> CONTRATOid
		{
			get
			{
				return this._CONTRATOid;
			}
			set
			{
				if ((this._CONTRATOid != value))
				{
					if (this._CONTRATO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCONTRATOidChanging(value);
					this.SendPropertyChanging();
					this._CONTRATOid = value;
					this.SendPropertyChanged("CONTRATOid");
					this.OnCONTRATOidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_PARCELA_NUM", DbType="Int NOT NULL")]
		public int PGTO_PARCELA_NUM
		{
			get
			{
				return this._PGTO_PARCELA_NUM;
			}
			set
			{
				if ((this._PGTO_PARCELA_NUM != value))
				{
					this.OnPGTO_PARCELA_NUMChanging(value);
					this.SendPropertyChanging();
					this._PGTO_PARCELA_NUM = value;
					this.SendPropertyChanged("PGTO_PARCELA_NUM");
					this.OnPGTO_PARCELA_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="Date NOT NULL")]
		public System.DateTime DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this.OnDATAChanging(value);
					this.SendPropertyChanging();
					this._DATA = value;
					this.SendPropertyChanged("DATA");
					this.OnDATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Float NOT NULL")]
		public double VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGTO_STATUS", DbType="Bit NOT NULL")]
		public bool PAGTO_STATUS
		{
			get
			{
				return this._PAGTO_STATUS;
			}
			set
			{
				if ((this._PAGTO_STATUS != value))
				{
					this.OnPAGTO_STATUSChanging(value);
					this.SendPropertyChanging();
					this._PAGTO_STATUS = value;
					this.SendPropertyChanged("PAGTO_STATUS");
					this.OnPAGTO_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_VENC", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string CONTRATO_VENC
		{
			get
			{
				return this._CONTRATO_VENC;
			}
			set
			{
				if ((this._CONTRATO_VENC != value))
				{
					this.OnCONTRATO_VENCChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_VENC = value;
					this.SendPropertyChanged("CONTRATO_VENC");
					this.OnCONTRATO_VENCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONTRATO_PAGAMENTO", Storage="_CONTRATO", ThisKey="CONTRATOid", OtherKey="CONTRATOid", IsForeignKey=true)]
		public CONTRATO CONTRATO
		{
			get
			{
				return this._CONTRATO.Entity;
			}
			set
			{
				CONTRATO previousValue = this._CONTRATO.Entity;
				if (((previousValue != value) 
							|| (this._CONTRATO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONTRATO.Entity = null;
						previousValue.PAGAMENTOs.Remove(this);
					}
					this._CONTRATO.Entity = value;
					if ((value != null))
					{
						value.PAGAMENTOs.Add(this);
						this._CONTRATOid = value.CONTRATOid;
					}
					else
					{
						this._CONTRATOid = default(Nullable<int>);
					}
					this.SendPropertyChanged("CONTRATO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Endereco")]
	public partial class Endereco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENDid;
		
		private int _CADid;
		
		private string _RUA;
		
		private string _NUMERO;
		
		private string _COMPLEMENTO;
		
		private string _CEP;
		
		private string _BAIRRO;
		
		private string _CIDADE;
		
		private string _UF;
		
		private EntityRef<CADASTRO> _CADASTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENDidChanging(int value);
    partial void OnENDidChanged();
    partial void OnCADidChanging(int value);
    partial void OnCADidChanged();
    partial void OnRUAChanging(string value);
    partial void OnRUAChanged();
    partial void OnNUMEROChanging(string value);
    partial void OnNUMEROChanged();
    partial void OnCOMPLEMENTOChanging(string value);
    partial void OnCOMPLEMENTOChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    #endregion
		
		public Endereco()
		{
			this._CADASTRO = default(EntityRef<CADASTRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ENDid
		{
			get
			{
				return this._ENDid;
			}
			set
			{
				if ((this._ENDid != value))
				{
					this.OnENDidChanging(value);
					this.SendPropertyChanging();
					this._ENDid = value;
					this.SendPropertyChanged("ENDid");
					this.OnENDidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CADid", DbType="Int")]
		public int CADid
		{
			get
			{
				return this._CADid;
			}
			set
			{
				if ((this._CADid != value))
				{
					if (this._CADASTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCADidChanging(value);
					this.SendPropertyChanging();
					this._CADid = value;
					this.SendPropertyChanged("CADid");
					this.OnCADidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUA", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string RUA
		{
			get
			{
				return this._RUA;
			}
			set
			{
				if ((this._RUA != value))
				{
					this.OnRUAChanging(value);
					this.SendPropertyChanging();
					this._RUA = value;
					this.SendPropertyChanged("RUA");
					this.OnRUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this.OnNUMEROChanging(value);
					this.SendPropertyChanging();
					this._NUMERO = value;
					this.SendPropertyChanged("NUMERO");
					this.OnNUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLEMENTO", DbType="VarChar(50)")]
		public string COMPLEMENTO
		{
			get
			{
				return this._COMPLEMENTO;
			}
			set
			{
				if ((this._COMPLEMENTO != value))
				{
					this.OnCOMPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._COMPLEMENTO = value;
					this.SendPropertyChanged("COMPLEMENTO");
					this.OnCOMPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_Endereco", Storage="_CADASTRO", ThisKey="CADid", OtherKey="CADid", IsForeignKey=true)]
		public CADASTRO CADASTRO
		{
			get
			{
				return this._CADASTRO.Entity;
			}
			set
			{
				CADASTRO previousValue = this._CADASTRO.Entity;
				if (((previousValue != value) 
							|| (this._CADASTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CADASTRO.Entity = null;
						previousValue.Enderecos.Remove(this);
					}
					this._CADASTRO.Entity = value;
					if ((value != null))
					{
						value.Enderecos.Add(this);
						this._CADid = value.CADid;
					}
					else
					{
						this._CADid = default(int);
					}
					this.SendPropertyChanged("CADASTRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONTRATO")]
	public partial class CONTRATO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONTRATOid;
		
		private string _CPFCNPJ;
		
		private System.Nullable<int> _CADid;
		
		private int _CONTRATO_QTDE_PARCELAS;
		
		private double _CONTRATO_VALOR;
		
		private double _CONTRATO_TX_JUROS;
		
		private string _CONTRATO_STATUS;
		
		private string _CONTRATO_VENC;
		
		private EntitySet<PAGAMENTO> _PAGAMENTOs;
		
		private EntityRef<CADASTRO> _CADASTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONTRATOidChanging(int value);
    partial void OnCONTRATOidChanged();
    partial void OnCPFCNPJChanging(string value);
    partial void OnCPFCNPJChanged();
    partial void OnCADidChanging(System.Nullable<int> value);
    partial void OnCADidChanged();
    partial void OnCONTRATO_QTDE_PARCELASChanging(int value);
    partial void OnCONTRATO_QTDE_PARCELASChanged();
    partial void OnCONTRATO_VALORChanging(double value);
    partial void OnCONTRATO_VALORChanged();
    partial void OnCONTRATO_TX_JUROSChanging(double value);
    partial void OnCONTRATO_TX_JUROSChanged();
    partial void OnCONTRATO_STATUSChanging(string value);
    partial void OnCONTRATO_STATUSChanged();
    partial void OnCONTRATO_VENCChanging(string value);
    partial void OnCONTRATO_VENCChanged();
    #endregion
		
		public CONTRATO()
		{
			this._PAGAMENTOs = new EntitySet<PAGAMENTO>(new Action<PAGAMENTO>(this.attach_PAGAMENTOs), new Action<PAGAMENTO>(this.detach_PAGAMENTOs));
			this._CADASTRO = default(EntityRef<CADASTRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATOid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CONTRATOid
		{
			get
			{
				return this._CONTRATOid;
			}
			set
			{
				if ((this._CONTRATOid != value))
				{
					this.OnCONTRATOidChanging(value);
					this.SendPropertyChanging();
					this._CONTRATOid = value;
					this.SendPropertyChanged("CONTRATOid");
					this.OnCONTRATOidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCNPJ", DbType="VarChar(15)")]
		public string CPFCNPJ
		{
			get
			{
				return this._CPFCNPJ;
			}
			set
			{
				if ((this._CPFCNPJ != value))
				{
					this.OnCPFCNPJChanging(value);
					this.SendPropertyChanging();
					this._CPFCNPJ = value;
					this.SendPropertyChanged("CPFCNPJ");
					this.OnCPFCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CADid", DbType="Int")]
		public System.Nullable<int> CADid
		{
			get
			{
				return this._CADid;
			}
			set
			{
				if ((this._CADid != value))
				{
					if (this._CADASTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCADidChanging(value);
					this.SendPropertyChanging();
					this._CADid = value;
					this.SendPropertyChanged("CADid");
					this.OnCADidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_QTDE_PARCELAS", DbType="Int NOT NULL")]
		public int CONTRATO_QTDE_PARCELAS
		{
			get
			{
				return this._CONTRATO_QTDE_PARCELAS;
			}
			set
			{
				if ((this._CONTRATO_QTDE_PARCELAS != value))
				{
					this.OnCONTRATO_QTDE_PARCELASChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_QTDE_PARCELAS = value;
					this.SendPropertyChanged("CONTRATO_QTDE_PARCELAS");
					this.OnCONTRATO_QTDE_PARCELASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_VALOR", DbType="Float NOT NULL")]
		public double CONTRATO_VALOR
		{
			get
			{
				return this._CONTRATO_VALOR;
			}
			set
			{
				if ((this._CONTRATO_VALOR != value))
				{
					this.OnCONTRATO_VALORChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_VALOR = value;
					this.SendPropertyChanged("CONTRATO_VALOR");
					this.OnCONTRATO_VALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_TX_JUROS", DbType="Float NOT NULL")]
		public double CONTRATO_TX_JUROS
		{
			get
			{
				return this._CONTRATO_TX_JUROS;
			}
			set
			{
				if ((this._CONTRATO_TX_JUROS != value))
				{
					this.OnCONTRATO_TX_JUROSChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_TX_JUROS = value;
					this.SendPropertyChanged("CONTRATO_TX_JUROS");
					this.OnCONTRATO_TX_JUROSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_STATUS", DbType="VarChar(40)")]
		public string CONTRATO_STATUS
		{
			get
			{
				return this._CONTRATO_STATUS;
			}
			set
			{
				if ((this._CONTRATO_STATUS != value))
				{
					this.OnCONTRATO_STATUSChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_STATUS = value;
					this.SendPropertyChanged("CONTRATO_STATUS");
					this.OnCONTRATO_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO_VENC", DbType="VarChar(40)")]
		public string CONTRATO_VENC
		{
			get
			{
				return this._CONTRATO_VENC;
			}
			set
			{
				if ((this._CONTRATO_VENC != value))
				{
					this.OnCONTRATO_VENCChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO_VENC = value;
					this.SendPropertyChanged("CONTRATO_VENC");
					this.OnCONTRATO_VENCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONTRATO_PAGAMENTO", Storage="_PAGAMENTOs", ThisKey="CONTRATOid", OtherKey="CONTRATOid")]
		public EntitySet<PAGAMENTO> PAGAMENTOs
		{
			get
			{
				return this._PAGAMENTOs;
			}
			set
			{
				this._PAGAMENTOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CADASTRO_CONTRATO", Storage="_CADASTRO", ThisKey="CADid", OtherKey="CADid", IsForeignKey=true)]
		public CADASTRO CADASTRO
		{
			get
			{
				return this._CADASTRO.Entity;
			}
			set
			{
				CADASTRO previousValue = this._CADASTRO.Entity;
				if (((previousValue != value) 
							|| (this._CADASTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CADASTRO.Entity = null;
						previousValue.CONTRATOs.Remove(this);
					}
					this._CADASTRO.Entity = value;
					if ((value != null))
					{
						value.CONTRATOs.Add(this);
						this._CADid = value.CADid;
					}
					else
					{
						this._CADid = default(Nullable<int>);
					}
					this.SendPropertyChanged("CADASTRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PAGAMENTOs(PAGAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.CONTRATO = this;
		}
		
		private void detach_PAGAMENTOs(PAGAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.CONTRATO = null;
		}
	}
}
#pragma warning restore 1591
